### ISSUE TITLE
Mismatch between paper and repo - data preparation details needed

### ISSUE THREAD

**Issue by dkajtoch** [xliuhw/NLU-Evaluation-Data#5]
Thanks for the great dataset! I would like to add it into [huggingface/datasets](https://github.com/huggingface/datasets) repo and I need a few clarifications. Specifically, I want to add this [annotated data](https://github.com/xliuhw/NLU-Evaluation-Data/blob/master/AnnotatedData/NLU-Data-Home-Domain-Annotated-All.csv) and  have problems with counting:
1. The dataset has 25716 rows with 18 unique `scenario` and 54 `intent`. According to [this issue](https://github.com/xliuhw/NLU-Evaluation-Data/issues/3) scenario is not a domain. Can we make a mapping from domain to scenario? 
2. Intent name seems to be a [concatenation of scenario and intent columns](https://github.com/xliuhw/NLU-Evaluation-Data/blob/master/CrossValidation/out4WatsonReal/Watson_2018_03_22-13_01_25_169_trainset/CrossValidation/KFold_1/merged/intents/WatsonNluIntentsMerged_2018_03_22-13_01_25_169.csv). This procedure will result in 68 unique intent names (not 64). Did you drop some intents (like e.g. volume_other or dislikeness) or merged them into other?

@xliuhw

**Comment by xliuhw** [comment]
Thanks for your questions!

1.
The 'domain' reported in the paper was relative to the original data(as explained in the answer to the Issue #3), some of the them were merged into one 'scenario' in the annotated data for better clarifications. The main merged one is 'play' scenario which including the 'podcasts', 'radio', 'music'(part of its contents) and 'game' domains from the original data.

I've listed the domain names and scenario names in the answer to the Issue #3. From there you can see some mapping relations. The contents of the 18 scenarios cover the contents of the 21 domains. I don't know your use cases so don't know why the domain names or number of domains matter in your use case. The scenario column in the annotated data is important in term of the final evaluation because it will be concatenated with the intent column to generate the final NLU intents.

2.
Yes, it is the concatenation of both columns. Yes, it results in 68 unique final NLU intents, but the 64 intents reported in the paper was the final intents we used for the NLU platform evaluations. There are some conditions in the processing scripts e.g. minimum number of the utterance in each intent, so some intents were dropped so that the intent number of the final evaluation was 64.

Hope the answers above help.

**Comment by dkajtoch** [comment]
Thank you very much for your answer! I think that it is good to include just a raw part of the dataset in the repo huggingface with a little preprocessing. 
I will take either: https://github.com/xliuhw/NLU-Evaluation-Scripts/blob/356711b59f347532d0290f070ff9aad5af7ed02e/resources/input-csv/AnnotatedData_MergedAll.csv or https://github.com/xliuhw/NLU-Evaluation-Data/blob/master/AnnotatedData/NLU-Data-Home-Domain-Annotated-All.csv (they are the same) as the base dataset and extract answers from `annotated_answer` and define intent as concat of `scenario` and `intent` columns.

This gives me exactly: 25715 (one row was without annotated_answer or any answer) with 68 intents.

**Comment by xliuhw** [comment]
Okay, thanks! I close the Issue for now. Please feel free to reopen it or raise other questions if you'd like to.
